In [3]:
from sklearn import datasets
#引入决策树算法包
from sklearn.neural_network import MLPClassifier
import numpy as np
#引入画图相关的包
from IPython.display import Image
from sklearn import tree
#dot是一个程序化生成流程图的简单语言
import pydotplus


In [4]:
np.random.seed(0)
iris=datasets.load_iris()
iris_x=iris.data
iris_y=iris.target
#print(iris_x)
indices=np.random.permutation(len(iris_x))
iris_x_train=iris_x[indices[:-10]]
iris_y_train=iris_y[indices[:-10]]
iris_x_test=iris_x[indices[-10:]]
iris_y_test=iris_y[indices[-10:]]

In [ ]:
# solver是权重优化策略，
# avtivation表示选择的激活函数，这里没有设置，默认是relu;
# alpha是惩罚参数，hidden_layer_sizes是隐藏层的数量，每一个大小就是设置每层隐藏层的神经元数量，
# random_state是初始化所使用的随机项

In [12]:
#clf=MLPClassifier(solver='lbfgs',alpha=1e-5,hidden_layer_sizes=(5,2),random_state=1)
#clf=MLPClassifier(solver='lbfgs',alpha=1e-5,hidden_layer_sizes=(10,10,10),random_state=1)
clf=MLPClassifier(solver='lbfgs',alpha=1e-5,hidden_layer_sizes=(20,20,20,20),random_state=1)
clf.fit(iris_x_train,iris_y_train)
iris_y_predict=clf.predict(iris_x_test)
score=clf.score(iris_x_test,iris_y_test,sample_weight=None)


In [7]:
print(iris_y_predict)
print(iris_y_test)
print('Accuracy',score)
print('layer nums：',clf.n_layers_)

[2 2 2 2 2 2 2 2 2 2]
[1 1 1 0 0 0 2 1 2 0]
Accuracy 0.2
layer nums： 4


In [9]:
print(iris_y_predict)
print(iris_y_test)
print('Accuracy',score)
print('layer nums：',clf.n_layers_)

[1 2 1 0 0 0 2 1 2 0]
[1 1 1 0 0 0 2 1 2 0]
Accuracy 0.9
layer nums： 5


In [13]:
print(iris_y_predict)
print(iris_y_test)
print('Accuracy',score)
print('layer nums：',clf.n_layers_)

[1 2 1 0 0 0 2 1 2 0]
[1 1 1 0 0 0 2 1 2 0]
Accuracy 0.9
layer nums： 6
